version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: books_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books
    ports:
      - "5432:5432"
    volumes:
      # Mount migrations for automatic execution on startup
      - ./book/postgres/migrations:/docker-entrypoint-initdb.d
      # Named volume for data persistence
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - books_network

networks:
  books_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
